### PR TITLE
Add TextAlign tool

### PR DESCRIPTION
**Pull request by codysaylor**
This change adds the correct buttons, but it does not yet update the textAlign attribute. It always remains "left" even after setting it with `editor.chain().focus().setTextAlign(alignment).run()`

### CODE REVIEW

**Comment by formfcw** [comment]
Thanks @codysaylor for contributing.
I’ve made some small changes. I am not able to push the changes to your branch, can you please give me write access?

After that …

To do:
- [ ] Shortcuts ([tiptap-extension](https://tiptap.dev/docs/editor/api/extensions/text-align#keyboard-shortcuts), [types](https://github.com/formfcw/directus-extension-flexible-editor/blob/5748639554e1cd93a0da8fe29ff95d4c271f5827/src/interface/types/tool.ts#L17))
- [ ] Menu
    - Instead of 4 individual buttons I would really like to see 1 button, that shows the current alignment. When you click it, a dropdown with all options appears. Have a look at: [types](https://github.com/formfcw/directus-extension-flexible-editor/blob/5748639554e1cd93a0da8fe29ff95d4c271f5827/src/interface/types/tool.ts#L18) and [table tool](https://github.com/formfcw/directus-extension-flexible-editor/blob/main/src/interface/components/ToolButtonTable.vue)
- [ ] Extension key should be camelCase (for consistency)
- [ ] Unresolved questions
    - How to set the default alignment if “Align Left” is disabled in the interface settings? Is it the first alignment option or should “Align Left” always be displayed?
    - Alternative: Provide only the option to enable TextAlign as a whole (without selecting left, right, center or justified individually)

**Comment by codysaylor** [comment]
@formfcw Thank you - I've sent the invite.

**Comment by formfcw** [comment]
Thanks! I’ve pushed it. Have a look at the commits (if you like)

**Comment by formfcw** [comment]
Would you like to work on the to-dos above?

**Comment by codysaylor** [comment]
Awesome, thank you. Yes I'll give them a shot!

**Comment by codysaylor** [comment]
@formfcw I've made some progress! I have two questions:

1. Cmd + shift + L is not setting the alignment to left. Do you know why?
2. The label defined in `custom-messages.ts` had to be hard-coded because I don't know what `$t:wysiwyg_options` is looking at.

**Comment by formfcw** [comment]
>     1. Cmd + shift + L is not setting the alignment to left. Do you know why?

It works for me.

>     2. The label defined in `custom-messages.ts` had to be hard-coded because I don't know what `$t:wysiwyg_options` is looking at.

It looks at the [i18n messages](https://github.com/directus/directus/blob/main/app/src/lang/translations/en-US.yaml) of the Directus core.

Let‘s continue the conversation at: https://github.com/formfcw/directus-extension-flexible-editor/pull/39

**Pull request merged**
